name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.2.2

              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}

                  script: |
                      set -e

                      cd ${{ secrets.APP_PATH }}

                      echo "Current Directory:"
                      pwd

                      git fetch --all
                      git reset --hard origin/main

                      composer install \
                        --no-dev \
                        --prefer-dist \
                        --no-interaction \
                        --optimize-autoloader

                      echo "Deploy Success"
