name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy to Production
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.2.2

              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}

                  script: |
                      set -e

                      echo "=================================="
                      echo "🚀 Deploy Nata App"
                      echo "=================================="

                      cd ${{ secrets.APP_PATH }}

                      echo ""
                      echo "📥 Update Repository"
                      git fetch origin
                      git reset --hard origin/main

                      echo ""
                      echo "📦 Install Composer"
                      composer install \
                        --no-dev \
                        --prefer-dist \
                        --no-interaction \
                        --optimize-autoloader

                      echo ""
             


                      echo ""
                      echo "📂 Copy Public Files"

                      cp -rf public/assets /home/u855axyw/public_html/

                      if [ -f public/.htaccess ]; then
                        cp public/.htaccess \
                          /home/u855axyw/public_html/.htaccess
                      fi

                      echo ""
                      echo "🔐 Set Permissions"



                      echo ""
                      echo "✅ Deploy Success"
